#!/bin/bash
# Too Many Coins - Setup Script
# This script sets up the game on a fresh Ubuntu server with Apache, PHP, and MySQL
# Run as root or with sudo

set -e

echo "============================================"
echo "  Too Many Coins - Server Setup"
echo "============================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
DB_NAME="${TMC_DB_NAME:-too_many_coins}"
DB_USER="${TMC_DB_USER:-tmc_user}"
DB_PASS="${TMC_DB_PASS:-$(openssl rand -hex 16)}"
INSTALL_DIR="${TMC_INSTALL_DIR:-/var/www/too-many-coins}"
DOMAIN="${TMC_DOMAIN:-_}"

echo ""
echo -e "${YELLOW}Configuration:${NC}"
echo "  Database: $DB_NAME"
echo "  DB User:  $DB_USER"
echo "  Install:  $INSTALL_DIR"
echo "  Domain:   $DOMAIN"
echo ""

# Step 1: Install dependencies
echo -e "${GREEN}[1/8] Installing dependencies...${NC}"
apt-get update -y
apt-get install -y apache2 php php-mysql php-json php-mbstring php-curl mysql-server

# Step 2: Start MySQL
echo -e "${GREEN}[2/8] Configuring MySQL...${NC}"
systemctl start mysql
systemctl enable mysql

# Create database and user
mysql -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME};"
mysql -e "CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';"
mysql -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';"
mysql -e "FLUSH PRIVILEGES;"

# Step 3: Load schema
echo -e "${GREEN}[3/8] Loading database schema...${NC}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mysql -e "USE ${DB_NAME}; SOURCE ${SCRIPT_DIR}/schema.sql;"
mysql -e "USE ${DB_NAME}; SOURCE ${SCRIPT_DIR}/seed_data.sql;"
mysql -e "USE ${DB_NAME}; SOURCE ${SCRIPT_DIR}/migration_boosts_drops.sql;"

# Add columns that the migration ALTER TABLE might fail on
mysql ${DB_NAME} -e "ALTER TABLE season_participation ADD COLUMN sigil_drops_total INT NOT NULL DEFAULT 0, ADD COLUMN eligible_ticks_since_last_drop BIGINT NOT NULL DEFAULT 0;" 2>/dev/null || true

echo -e "${GREEN}  Database loaded successfully.${NC}"

# Step 4: Install application files
echo -e "${GREEN}[4/8] Installing application files...${NC}"
mkdir -p ${INSTALL_DIR}
cp -r ${SCRIPT_DIR}/public/* ${INSTALL_DIR}/
cp -r ${SCRIPT_DIR}/api ${INSTALL_DIR}/
cp -r ${SCRIPT_DIR}/includes ${INSTALL_DIR}/

# Step 5: Configure database connection
echo -e "${GREEN}[5/8] Configuring database connection...${NC}"
cat > ${INSTALL_DIR}/includes/config.php << PHPEOF
<?php
// Too Many Coins - Configuration (Auto-generated by setup.sh)
define('DB_HOST', 'localhost');
define('DB_NAME', '${DB_NAME}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');

// Game Constants
define('TIME_SCALE', 60);
define('SEASON_DURATION_TICKS', 2419200);
define('SEASON_STAGGER_TICKS', 604800);
define('BLACKOUT_DURATION_TICKS', 259200);
define('SEASON_ANCHOR', 60);
define('MAX_SEASONS', 3);
define('IDLE_TIMEOUT_TICKS', 54000);
define('TRADE_EXPIRY_TICKS', 86400);

// Fixed-point scale (1,000,000 = 1.0)
define('FP_SCALE', 1000000);

// Sigil drop constants (from Chapter 04)
define('SIGIL_DROP_RATE', 50000);
define('SIGIL_PITY_TICKS', 120000);
define('SIGIL_MAX_DROPS_WINDOW', 3);
define('SIGIL_DROP_WINDOW_TICKS', 86400);

// Sigil tier odds (per million)
define('SIGIL_TIER_ODDS', [
    1 => 700000,
    2 => 200000,
    3 => 80000,
    4 => 15000,
    5 => 5000,
]);

// Progression constants
define('PARTICIPATION_BONUS_DIVISOR', 1440);
define('PARTICIPATION_BONUS_CAP', 500);
define('PLACEMENT_BONUS', [
    1 => 1000,
    2 => 500,
    3 => 250,
]);
PHPEOF

# Step 6: Set permissions
echo -e "${GREEN}[6/8] Setting file permissions...${NC}"
chown -R www-data:www-data ${INSTALL_DIR}
chmod -R 755 ${INSTALL_DIR}

# Step 7: Configure Apache
echo -e "${GREEN}[7/8] Configuring Apache...${NC}"
cat > /etc/apache2/sites-available/too-many-coins.conf << APACHEEOF
<VirtualHost *:80>
    ServerName ${DOMAIN}
    DocumentRoot ${INSTALL_DIR}
    
    <Directory ${INSTALL_DIR}>
        AllowOverride All
        Require all granted
        Options -Indexes +FollowSymLinks
    </Directory>
    
    # Route API requests
    <Directory ${INSTALL_DIR}/api>
        AllowOverride All
        Require all granted
    </Directory>
    
    # Deny access to includes
    <Directory ${INSTALL_DIR}/includes>
        Require all denied
    </Directory>
    
    ErrorLog \${APACHE_LOG_DIR}/tmc_error.log
    CustomLog \${APACHE_LOG_DIR}/tmc_access.log combined
</VirtualHost>
APACHEEOF

# Create .htaccess for SPA routing
cat > ${INSTALL_DIR}/.htaccess << HTEOF
RewriteEngine On
RewriteBase /

# Don't rewrite existing files/dirs
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# Don't rewrite API calls
RewriteCond %{REQUEST_URI} !^/api/

# Route everything else to index.html
RewriteRule ^(.*)$ /index.html [L]
HTEOF

a2enmod rewrite
a2dissite 000-default 2>/dev/null || true
a2ensite too-many-coins
systemctl restart apache2
systemctl enable apache2

# Step 8: Setup cron for tick processing
echo -e "${GREEN}[8/8] Setting up tick processing cron...${NC}"
cat > /etc/cron.d/too-many-coins << CRONEOF
# Process game ticks every 30 seconds
* * * * * www-data php ${INSTALL_DIR}/api/index.php action=game_state > /dev/null 2>&1
* * * * * www-data sleep 30 && php ${INSTALL_DIR}/api/index.php action=game_state > /dev/null 2>&1
CRONEOF

echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}  Too Many Coins - Setup Complete!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo -e "  Database: ${DB_NAME}"
echo -e "  DB User:  ${DB_USER}"
echo -e "  DB Pass:  ${YELLOW}${DB_PASS}${NC}"
echo -e "  URL:      http://${DOMAIN}"
echo -e "  Install:  ${INSTALL_DIR}"
echo ""
echo -e "${YELLOW}IMPORTANT: Save the database password above!${NC}"
echo ""
echo "To use with a domain name, update /etc/apache2/sites-available/too-many-coins.conf"
echo "and set ServerName to your domain. Then set up SSL with: certbot --apache -d yourdomain.com"
echo ""
